#include "stdafx.h"
#include "awsdk_attributemap.h"
#include "awsdk_bot.h"
#include "aw.h"

#define MAP_ATTR(attr, type)				\
	m_items[attr].attribute_id	= attr;				\
	m_items[attr].name			= #attr;			\
	m_items[attr].var_type		= type;

namespace AW
{
	const int AT_NONE		= 0;
	const int AT_INT		= 1;
	const int AT_STRING		= 2;
	const int AT_FLOAT		= 3;
	const int AT_HEX		= 4;
	const int AT_TIME		= 5;
	const int AT_RGB		= 6;
	const int AT_IP			= 7;
	const int AT_BOOL		= 8;

	String AttributeMap::AttributeToString(int ID)
	{
		int				elem_type = m_items[ID].var_type;
		AW_ATTRIBUTE 	attrID	  = (AW_ATTRIBUTE)ID;
		String log;

		switch (elem_type)
		{
		case AT_NONE:
			return "";

		case AT_STRING:
			return m_pSourceBot->_string(attrID);

		case AT_INT:
			log.Format("%d", m_pSourceBot->_int(attrID));
			return log;

		case AT_BOOL:
			return m_pSourceBot->_bool(attrID) ? "TRUE" : "FALSE";

		case AT_FLOAT:
			log.Format("%.3f", m_pSourceBot->_float(attrID));
			return log;

		case AT_HEX:
			log.Format("%X", m_pSourceBot->_int(attrID));
			return log;

		case AT_TIME:
		{
			CTime tm = m_pSourceBot->_int(attrID);
			return tm.Format("%#c");
		}

		case AT_RGB:
			log.Format("%x", m_pSourceBot->_int(attrID));
			return log;

		case AT_IP:
			log.Format("%x", m_pSourceBot->_int(attrID));
			return log;

		default:
			log.Format("%d", m_pSourceBot->_int(attrID));
			return log;
		};
	}

	void AttributeMap::UpdateAll()
	{
		for (int i = 0; i < AW_MAX_ATTRIBUTE; i++)
			m_items[i].text = AttributeToString(i);
	}

	AttributeMap::AttributeMap()
	{
		MAP_ATTR( AW_LOGIN_NAME,						AT_STRING);						
		MAP_ATTR( AW_LOGIN_PASSWORD,					AT_STRING);
		MAP_ATTR( AW_LOGIN_OWNER,						AT_INT);
		MAP_ATTR( AW_LOGIN_PRIVILEGE_PASSWORD,			AT_STRING);
		MAP_ATTR( AW_LOGIN_PRIVILEGE_NUMBER,			AT_INT);
		MAP_ATTR( AW_LOGIN_PRIVILEGE_NAME,				AT_STRING);
		MAP_ATTR( AW_LOGIN_APPLICATION,					AT_STRING);
		MAP_ATTR( AW_LOGIN_EMAIL,						AT_STRING);
		MAP_ATTR( AW_UNIVERSE_BROWSER_MINIMUM,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_BROWSER_RELEASE,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_BROWSER_BETA,				AT_INT);
		MAP_ATTR( AW_UNIVERSE_WORLD_MINIMUM,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_WORLD_START,				AT_STRING);
		MAP_ATTR( AW_UNIVERSE_REGISTRATION_REQUIRED,	AT_BOOL);
		MAP_ATTR( AW_UNIVERSE_BUILD_NUMBER,				AT_INT);
		MAP_ATTR( AW_UNIVERSE_MONTHLY_CHARGE,			AT_STRING);
		MAP_ATTR( AW_UNIVERSE_ANNUAL_CHARGE,			AT_STRING);
		MAP_ATTR( AW_UNIVERSE_REGISTER_METHOD,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_TIME,						AT_INT);
		MAP_ATTR( AW_UNIVERSE_CITIZEN_CHANGES_ALLOWED,	AT_BOOL);
		MAP_ATTR( AW_UNIVERSE_BROWSER_RELEASE_22,		AT_INT);
		MAP_ATTR( AW_UNIVERSE_WELCOME_MESSAGE,			AT_STRING);
		MAP_ATTR( AW_UNIVERSE_WORLD_RELEASE,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_WORLD_BETA,				AT_INT);
		MAP_ATTR( AW_UNIVERSE_ALLOW_TOURISTS,			AT_INT);
		MAP_ATTR( AW_UNIVERSE_SEARCH_URL,				AT_STRING);
		MAP_ATTR( AW_UNIVERSE_NOTEPAD_URL,				AT_STRING);
		MAP_ATTR( AW_UNIVERSE_NAME,						AT_STRING);
		MAP_ATTR( AW_UNIVERSE_USER_LIST_ENABLED,		AT_BOOL);
		MAP_ATTR( AW_CITIZEN_NUMBER,					AT_INT);
		MAP_ATTR( AW_CITIZEN_NAME,						AT_STRING);	
		MAP_ATTR( AW_CITIZEN_PASSWORD,					AT_STRING);
		MAP_ATTR( AW_CITIZEN_EMAIL,						AT_STRING);
		MAP_ATTR( AW_CITIZEN_TIME_LEFT,					AT_INT);
		MAP_ATTR( AW_CITIZEN_PRIVILEGE_PASSWORD,		AT_STRING);
		MAP_ATTR( AW_CITIZEN_IMMIGRATION_TIME,			AT_TIME);
		MAP_ATTR( AW_CITIZEN_EXPIRATION_TIME,			AT_TIME);
		MAP_ATTR( AW_CITIZEN_BETA,						AT_INT);
		MAP_ATTR( AW_CITIZEN_LAST_LOGIN,				AT_INT);
		MAP_ATTR( AW_CITIZEN_BOT_LIMIT,					AT_INT);
		MAP_ATTR( AW_CITIZEN_TOTAL_TIME,				AT_INT);
		MAP_ATTR( AW_CITIZEN_ENABLED,					AT_INT);
		MAP_ATTR( AW_CITIZEN_COMMENT,					AT_STRING);
		MAP_ATTR( AW_CITIZEN_URL,						AT_STRING);
		MAP_ATTR( AW_WORLD_NAME,						AT_STRING);	
		MAP_ATTR( AW_WORLD_TITLE,						AT_STRING);
		MAP_ATTR( AW_WORLD_BACKDROP,					AT_STRING);
		MAP_ATTR( AW_WORLD_GROUND,						AT_STRING);
		MAP_ATTR( AW_WORLD_OBJECT_PATH,					AT_STRING);
		MAP_ATTR( AW_WORLD_OBJECT_REFRESH,				AT_INT);
		MAP_ATTR( AW_WORLD_BUILD_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_EMINENT_DOMAIN_RIGHT,		AT_STRING);
		MAP_ATTR( AW_WORLD_ENTER_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_SPECIAL_OBJECTS_RIGHT,		AT_STRING);
		MAP_ATTR( AW_WORLD_FOG_RED,						AT_INT);
		MAP_ATTR( AW_WORLD_FOG_GREEN,					AT_INT);
		MAP_ATTR( AW_WORLD_FOG_BLUE,					AT_INT);
		MAP_ATTR( AW_WORLD_CARETAKER_CAPABILITY,		AT_BOOL);
		MAP_ATTR( AW_WORLD_RESTRICTED_RADIUS,			AT_INT);
		MAP_ATTR( AW_WORLD_PUBLIC_SPEAKER_CAPABILITY,	AT_BOOL);
		MAP_ATTR( AW_WORLD_PUBLIC_SPEAKER_RIGHT,		AT_STRING);
		MAP_ATTR( AW_WORLD_CREATION_TIMESTAMP,			AT_TIME);
		MAP_ATTR( AW_WORLD_HOME_PAGE,					AT_STRING);
		MAP_ATTR( AW_WORLD_BUILD_NUMBER,				AT_INT);
		MAP_ATTR( AW_WORLD_OBJECT_PASSWORD,				AT_STRING);
		MAP_ATTR( AW_WORLD_DISABLE_CREATE_URL,			AT_BOOL);
		MAP_ATTR( AW_WORLD_RATING,						AT_INT);
		MAP_ATTR( AW_WORLD_WELCOME_MESSAGE,				AT_STRING);
		MAP_ATTR( AW_WORLD_EJECT_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_EJECT_CAPABILITY,			AT_BOOL);
		MAP_ATTR( AW_WORLD_CELL_LIMIT,					AT_INT);
		MAP_ATTR( AW_WORLD_BUILD_CAPABILITY,			AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_PASSTHRU,				AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_FLYING,				AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_TELEPORT,				AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_OBJECT_SELECT,			AT_BOOL);
		MAP_ATTR( AW_WORLD_BOTS_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_SPEAK_CAPABILITY,			AT_BOOL);
		MAP_ATTR( AW_WORLD_SPEAK_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_ALLOW_TOURIST_WHISPER,		AT_BOOL);
		MAP_ATTR( AW_WORLD_LIGHT_X,						AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_Y,						AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_Z,						AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_RED,					AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_GREEN,					AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_BLUE,					AT_INT);
		MAP_ATTR( AW_WORLD_AMBIENT_LIGHT_RED,			AT_INT);
		MAP_ATTR( AW_WORLD_AMBIENT_LIGHT_GREEN,			AT_INT);
		MAP_ATTR( AW_WORLD_AMBIENT_LIGHT_BLUE,			AT_INT);
		MAP_ATTR( AW_WORLD_ALLOW_AVATAR_COLLISION,		AT_BOOL);
		MAP_ATTR( AW_WORLD_FOG_ENABLE,					AT_BOOL);
		MAP_ATTR( AW_WORLD_FOG_MINIMUM,					AT_INT);
		MAP_ATTR( AW_WORLD_FOG_MAXIMUM,					AT_INT);
		MAP_ATTR( AW_WORLD_FOG_TINTED,					AT_BOOL);
		MAP_ATTR( AW_WORLD_MAX_USERS,					AT_INT);
		MAP_ATTR( AW_WORLD_SIZE,						AT_INT);
		MAP_ATTR( AW_WORLD_OBJECT_COUNT,				AT_INT);
		MAP_ATTR( AW_WORLD_EXPIRATION,					AT_TIME);
		MAP_ATTR( AW_WORLD_SPECIAL_COMMANDS_RIGHT,		AT_STRING);
		MAP_ATTR( AW_WORLD_MAX_LIGHT_RADIUS,			AT_INT);
		MAP_ATTR( AW_WORLD_SKYBOX,						AT_STRING);
		MAP_ATTR( AW_WORLD_MINIMUM_VISIBILITY,			AT_INT);
		MAP_ATTR( AW_WORLD_REPEATING_GROUND,			AT_BOOL);
		MAP_ATTR( AW_WORLD_KEYWORDS,					AT_STRING);
		MAP_ATTR( AW_WORLD_ENABLE_TERRAIN,				AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_3_AXIS_ROTATION,		AT_BOOL);
		MAP_ATTR( AW_WORLD_TERRAIN_TIMESTAMP,			AT_INT);
		MAP_ATTR( AW_WORLD_ENTRY_POINT,					AT_STRING);
		MAP_ATTR( AW_WORLD_SKY_NORTH_RED,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_NORTH_GREEN,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_NORTH_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_SOUTH_RED,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_SOUTH_GREEN,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_SOUTH_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_EAST_RED,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_EAST_GREEN,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_EAST_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_WEST_RED,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_WEST_GREEN,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_WEST_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_TOP_RED,					AT_INT);
		MAP_ATTR( AW_WORLD_SKY_TOP_GREEN,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_TOP_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_BOTTOM_RED,				AT_INT);
		MAP_ATTR( AW_WORLD_SKY_BOTTOM_GREEN,			AT_INT);
		MAP_ATTR( AW_WORLD_SKY_BOTTOM_BLUE,				AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_TEXTURE,		AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_MASK,			AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_TILE,			AT_FLOAT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_SPEED_X,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_SPEED_Z,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER1_OPACITY,		AT_FLOAT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_TEXTURE,		AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_MASK,			AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_TILE,			AT_FLOAT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_SPEED_X,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_SPEED_Z,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER2_OPACITY,		AT_FLOAT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_TEXTURE,		AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_MASK,			AT_STRING);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_TILE,			AT_FLOAT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_SPEED_X,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_SPEED_Z,		AT_INT);
		MAP_ATTR( AW_WORLD_CLOUDS_LAYER3_OPACITY,		AT_FLOAT);
		MAP_ATTR( AW_WORLD_DISABLE_CHAT,				AT_BOOL);
		MAP_ATTR( AW_WORLD_ALLOW_CITIZEN_WHISPER,		AT_BOOL);
		MAP_ATTR( AW_WORLD_ALWAYS_SHOW_NAMES,			AT_STRING);
		MAP_ATTR( AW_WORLD_DISABLE_AVATAR_LIST,			AT_BOOL);
		MAP_ATTR( AW_WORLD_AVATAR_REFRESH_RATE,			AT_INT);
		MAP_ATTR( AW_WORLD_WATER_TEXTURE,				AT_STRING);
		MAP_ATTR( AW_WORLD_WATER_MASK,					AT_STRING);
		MAP_ATTR( AW_WORLD_WATER_BOTTOM_TEXTURE,		AT_STRING);
		MAP_ATTR( AW_WORLD_WATER_BOTTOM_MASK,			AT_STRING);
		MAP_ATTR( AW_WORLD_WATER_OPACITY,				AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_RED,					AT_INT);
		MAP_ATTR( AW_WORLD_WATER_GREEN,					AT_INT);
		MAP_ATTR( AW_WORLD_WATER_BLUE,					AT_INT);
		MAP_ATTR( AW_WORLD_WATER_LEVEL,					AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_SURFACE_MOVE,			AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_WAVE_MOVE,				AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_SPEED,					AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_ENABLED,				AT_BOOL);
		MAP_ATTR( AW_WORLD_EMINENT_DOMAIN_CAPABILITY,	AT_BOOL);
		MAP_ATTR( AW_WORLD_LIGHT_TEXTURE,				AT_STRING);
		MAP_ATTR( AW_WORLD_LIGHT_MASK,					AT_STRING);
		MAP_ATTR( AW_WORLD_LIGHT_DRAW_SIZE,				AT_INT);
		MAP_ATTR( AW_WORLD_LIGHT_DRAW_FRONT,			AT_BOOL);
		MAP_ATTR( AW_WORLD_LIGHT_DRAW_BRIGHT,			AT_BOOL);
		MAP_ATTR( AW_WORLD_LIGHT_SOURCE_USE_COLOR,		AT_BOOL);
		MAP_ATTR( AW_WORLD_LIGHT_SOURCE_COLOR,			AT_RGB);
		MAP_ATTR( AW_WORLD_TERRAIN_AMBIENT,				AT_FLOAT);
		MAP_ATTR( AW_WORLD_TERRAIN_DIFFUSE,				AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_VISIBILITY,			AT_INT);
		MAP_ATTR( AW_WORLD_SOUND_FOOTSTEP,				AT_STRING);
		MAP_ATTR( AW_WORLD_SOUND_WATER_ENTER,			AT_STRING);
		MAP_ATTR( AW_WORLD_SOUND_WATER_EXIT,			AT_STRING);
		MAP_ATTR( AW_WORLD_SOUND_AMBIENT,				AT_STRING);
		MAP_ATTR( AW_WORLD_GRAVITY,						AT_FLOAT);
		MAP_ATTR( AW_WORLD_BUOYANCY,					AT_FLOAT);
		MAP_ATTR( AW_WORLD_FRICTION,					AT_FLOAT);
		MAP_ATTR( AW_WORLD_WATER_FRICTION,				AT_FLOAT);
		MAP_ATTR( AW_WORLD_SLOPESLIDE_ENABLED,			AT_BOOL);
		MAP_ATTR( AW_WORLD_SLOPESLIDE_MIN_ANGLE,		AT_FLOAT);
		MAP_ATTR( AW_WORLD_SLOPESLIDE_MAX_ANGLE,		AT_FLOAT);
		MAP_ATTR( AW_WORLD_ALLOW_TOURIST_BUILD,			AT_BOOL);
		MAP_ATTR( AW_WORLD_ENABLE_REFERER,				AT_BOOL);
		MAP_ATTR( AW_WORLD_WATER_UNDER_TERRAIN,			AT_BOOL);
		MAP_ATTR( AW_WORLD_TERRAIN_OFFSET,				AT_INT);
		MAP_ATTR( AW_WORLD_VOIP_RIGHT,					AT_STRING);
		MAP_ATTR( AW_WORLD_DISABLE_MULTIPLE_MEDIA,		AT_BOOL);
		MAP_ATTR( AW_WORLD_BOTMENU_URL,					AT_STRING);
		MAP_ATTR( AW_WORLD_ENABLE_BUMP_EVENT,			AT_BOOL);
		MAP_ATTR( AW_WORLD_ENABLE_SYNC_EVENTS,			AT_BOOL);
		MAP_ATTR( AW_WORLD_ENABLE_CAV,					AT_BOOL);
		MAP_ATTR( AW_WORLD_ENABLE_PAV,					AT_BOOL);
		MAP_ATTR( AW_WORLD_CHAT_DISABLE_URL_CLICKS,		AT_BOOL);
		MAP_ATTR( AW_WORLD_MOVER_EMPTY_RESET_TIMEOUT,	AT_INT);
		MAP_ATTR( AW_WORLD_MOVER_USED_RESET_TIMEOUT,	AT_INT);
		MAP_ATTR( AW_MY_X,								AT_INT);
		MAP_ATTR( AW_MY_Y,								AT_INT);
		MAP_ATTR( AW_MY_Z,								AT_INT);
		MAP_ATTR( AW_MY_Y,								AT_INT);
		MAP_ATTR( AW_MY_PITCH,							AT_INT);
		MAP_ATTR( AW_MY_TYPE,							AT_INT);
		MAP_ATTR( AW_MY_GESTURE,						AT_INT);
		MAP_ATTR( AW_MY_STATE,							AT_INT);
		MAP_ATTR( AW_AVATAR_SESSION,					AT_INT);
		MAP_ATTR( AW_AVATAR_NAME,						AT_STRING);
		MAP_ATTR( AW_AVATAR_X,							AT_INT);
		MAP_ATTR( AW_AVATAR_Y,							AT_INT);
		MAP_ATTR( AW_AVATAR_Z,							AT_INT);
		MAP_ATTR( AW_AVATAR_Y,							AT_INT);
		MAP_ATTR( AW_AVATAR_PITCH,						AT_INT);
		MAP_ATTR( AW_AVATAR_TYPE,						AT_INT);
		MAP_ATTR( AW_AVATAR_GESTURE,					AT_INT);
		MAP_ATTR( AW_AVATAR_STATE,						AT_INT);
		MAP_ATTR( AW_AVATAR_ADDRESS,					AT_IP);
		MAP_ATTR( AW_AVATAR_VERSION,					AT_INT);
		MAP_ATTR( AW_AVATAR_CITIZEN,					AT_INT);
		MAP_ATTR( AW_AVATAR_PRIVILEGE,					AT_INT);
		MAP_ATTR( AW_AVATAR_LOCK,						AT_INT);
		MAP_ATTR( AW_AVATAR_FLAGS,						AT_INT);
		MAP_ATTR( AW_CHAT_SESSION,						AT_INT);
		MAP_ATTR( AW_CHAT_MESSAGE,						AT_STRING);
		MAP_ATTR( AW_CELL_X,							AT_INT);
		MAP_ATTR( AW_CELL_Z,							AT_INT);
		MAP_ATTR( AW_CELL_SEQUENCE,						AT_INT);
		MAP_ATTR( AW_CELL_SIZE,							AT_INT);
		MAP_ATTR( AW_CELL_ITERATOR,						AT_INT);
		MAP_ATTR( AW_CELL_COMBINE,						AT_INT);
		MAP_ATTR( AW_OBJECT_ID,							AT_INT);
		MAP_ATTR( AW_OBJECT_NUMBER,						AT_INT);
		MAP_ATTR( AW_OBJECT_X,							AT_INT);
		MAP_ATTR( AW_OBJECT_Y,							AT_INT);
		MAP_ATTR( AW_OBJECT_Z,							AT_INT);
		MAP_ATTR( AW_OBJECT_Y,							AT_INT);
		MAP_ATTR( AW_OBJECT_TILT,						AT_INT);
		MAP_ATTR( AW_OBJECT_ROLL,						AT_INT);
		MAP_ATTR( AW_OBJECT_MODEL,						AT_STRING);
		MAP_ATTR( AW_OBJECT_DESCRIPTION,				AT_STRING);
		MAP_ATTR( AW_OBJECT_ACTION,						AT_STRING);
		MAP_ATTR( AW_OBJECT_OLD_NUMBER,					AT_INT);
		MAP_ATTR( AW_OBJECT_OLD_X,						AT_INT);
		MAP_ATTR( AW_OBJECT_OLD_Z,						AT_INT);
		MAP_ATTR( AW_OBJECT_OWNER,						AT_INT);
		MAP_ATTR( AW_OBJECT_SESSION,					AT_INT);
		MAP_ATTR( AW_OBJECT_BUILD_TIMESTAMP,			AT_TIME);
		MAP_ATTR( AW_OBJECT_SYNC,						AT_BOOL);
		MAP_ATTR( AW_OBJECT_TYPE,						AT_INT);
		MAP_ATTR( AW_OBJECT_DATA,						AT_STRING);
		MAP_ATTR( AW_QUERY_COMPLETE,					AT_INT);
		MAP_ATTR( AW_CHAT_TYPE,							AT_BOOL);
		MAP_ATTR( AW_LICENSE_NAME,						AT_STRING);
		MAP_ATTR( AW_LICENSE_PASSWORD,					AT_STRING);
		MAP_ATTR( AW_LICENSE_USERS,						AT_INT);
		MAP_ATTR( AW_LICENSE_RANGE,						AT_INT);
		MAP_ATTR( AW_LICENSE_EMAIL,						AT_STRING);
		MAP_ATTR( AW_LICENSE_COMMENT,					AT_STRING);
		MAP_ATTR( AW_LICENSE_CREATION_TIME,				AT_TIME);
		MAP_ATTR( AW_LICENSE_EXPIRATION_TIME,			AT_TIME);
		MAP_ATTR( AW_LICENSE_LAST_START,				AT_TIME);
		MAP_ATTR( AW_LICENSE_LAST_ADDRESS,				AT_IP);
		MAP_ATTR( AW_LICENSE_HIDDEN,					AT_BOOL);
		MAP_ATTR( AW_LICENSE_ALLOW_TOURISTS,			AT_BOOL);
		MAP_ATTR( AW_LICENSE_VOIP,						AT_BOOL);
		MAP_ATTR( AW_LICENSE_PLUGINS,					AT_BOOL);
		MAP_ATTR( AW_WORLDLIST_NAME,					AT_STRING);
		MAP_ATTR( AW_WORLDLIST_STATUS,					AT_INT);
		MAP_ATTR( AW_WORLDLIST_USERS,					AT_INT);
		MAP_ATTR( AW_WORLDLIST_RATING,					AT_INT);
		MAP_ATTR( AW_WORLDLIST_MORE,					AT_BOOL);
		MAP_ATTR( AW_EJECT_SESSION,						AT_INT);
		MAP_ATTR( AW_EJECT_DURATION,					AT_INT);
		MAP_ATTR( AW_EJECTION_TYPE,						AT_INT);
		MAP_ATTR( AW_EJECTION_ADDRESS,					AT_INT);
		MAP_ATTR( AW_EJECTION_EXPIRATION_TIME,			AT_TIME);
		MAP_ATTR( AW_EJECTION_CREATION_TIME,			AT_TIME);
		MAP_ATTR( AW_EJECTION_COMMENT,					AT_STRING);
		MAP_ATTR( AW_DISCONNECT_REASON,					AT_INT);
		MAP_ATTR( AW_FILE_RECIPIENT,					AT_INT);
		MAP_ATTR( AW_FILE_SENDER,						AT_STRING);
		MAP_ATTR( AW_FILE_SENDER_NAME,					AT_STRING);
		MAP_ATTR( AW_FILE_SESSION,						AT_INT);
		MAP_ATTR( AW_FILE_ADDRESS,						AT_IP);
		MAP_ATTR( AW_FILE_PORT,							AT_INT);
		MAP_ATTR( AW_CLICKED_SESSION,					AT_INT);
		MAP_ATTR( AW_CLICKED_NAME,						AT_STRING);
		MAP_ATTR( AW_URL_NAME,							AT_STRING);
		MAP_ATTR( AW_URL_POST,							AT_STRING);
		MAP_ATTR( AW_URL_TARGET,						AT_STRING);
		MAP_ATTR( AW_URL_TARGET_3D,						AT_BOOL);
		MAP_ATTR( AW_TELEPORT_WORLD,					AT_STRING);
		MAP_ATTR( AW_TELEPORT_X,						AT_INT);
		MAP_ATTR( AW_TELEPORT_Y,						AT_INT);
		MAP_ATTR( AW_TELEPORT_Z,						AT_INT);
		MAP_ATTR( AW_TELEPORT_Y,						AT_INT);
		MAP_ATTR( AW_TELEPORT_WARP,						AT_BOOL);
		MAP_ATTR( AW_SERVER_BUILD,						AT_INT);
		MAP_ATTR( AW_SERVER_NAME,						AT_STRING);
		MAP_ATTR( AW_SERVER_PASSWORD,					AT_STRING);
		MAP_ATTR( AW_SERVER_REGISTRY,					AT_STRING);
		MAP_ATTR( AW_SERVER_CARETAKERS,					AT_STRING);
		MAP_ATTR( AW_SERVER_ID,							AT_INT);
		MAP_ATTR( AW_SERVER_INSTANCE,					AT_INT);
		MAP_ATTR( AW_SERVER_ENABLED,					AT_INT);
		MAP_ATTR( AW_SERVER_STATE,						AT_INT);
		MAP_ATTR( AW_SERVER_USERS,						AT_INT);
		MAP_ATTR( AW_SERVER_MAX_USERS,					AT_INT);
		MAP_ATTR( AW_SERVER_OBJECTS,					AT_INT);
		MAP_ATTR( AW_SERVER_SIZE,						AT_INT);
		MAP_ATTR( AW_SERVER_EXPIRATION,					AT_TIME);
		MAP_ATTR( AW_SERVER_START_RC,					AT_INT);
		MAP_ATTR( AW_SERVER_MORE,						AT_INT);
		MAP_ATTR( AW_SERVER_TERRAIN_NODES,				AT_INT);
		MAP_ATTR( AW_TERRAIN_X,							AT_INT);
		MAP_ATTR( AW_TERRAIN_Z,							AT_INT);
		MAP_ATTR( AW_TERRAIN_PAGE_X,					AT_INT);
		MAP_ATTR( AW_TERRAIN_PAGE_Z,					AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_X,					AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_Z,					AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_SIZE,					AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_TEXTURE_COUNT,		AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_HEIGHT_COUNT,			AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_TEXTURES,				AT_INT);
		MAP_ATTR( AW_TERRAIN_NODE_HEIGHTS,				AT_INT);
		MAP_ATTR( AW_TERRAIN_SEQUENCE,					AT_INT);
		MAP_ATTR( AW_TERRAIN_COMPLETE,					AT_BOOL);
		MAP_ATTR( AW_TERRAIN_VERSION_NEEDED,			AT_INT);
		MAP_ATTR( AW_ENTER_GLOBAL,						AT_BOOL);
		MAP_ATTR( AW_CONSOLE_RED,						AT_INT);
		MAP_ATTR( AW_CONSOLE_GREEN,						AT_INT);
		MAP_ATTR( AW_CONSOLE_BLUE,						AT_INT);
		MAP_ATTR( AW_CONSOLE_BOLD,						AT_BOOL);
		MAP_ATTR( AW_CONSOLE_ITALICS,					AT_BOOL);
		MAP_ATTR( AW_CONSOLE_MESSAGE,					AT_STRING);
		MAP_ATTR( AW_BOTGRAM_TO,						AT_INT);
		MAP_ATTR( AW_BOTGRAM_FROM,						AT_INT);
		MAP_ATTR( AW_BOTGRAM_FROM_NAME,					AT_STRING);
		MAP_ATTR( AW_BOTGRAM_TYPE,						AT_INT);
		MAP_ATTR( AW_BOTGRAM_TEXT,						AT_STRING);
		MAP_ATTR( AW_TOOLBAR_ID,						AT_INT);
		MAP_ATTR( AW_TOOLBAR_SESSION,					AT_INT);
		MAP_ATTR( AW_USERLIST_MORE,						AT_BOOL);
		MAP_ATTR( AW_USERLIST_NAME,						AT_STRING);
		MAP_ATTR( AW_USERLIST_WORLD,					AT_STRING);
		MAP_ATTR( AW_USERLIST_EMAIL,					AT_STRING);
		MAP_ATTR( AW_USERLIST_CITIZEN,					AT_INT);
		MAP_ATTR( AW_USERLIST_PRIVILEGE,				AT_INT);
		MAP_ATTR( AW_USERLIST_STATE,					AT_INT);
		MAP_ATTR( AW_USERLIST_ADDRESS,					AT_INT);
		MAP_ATTR( AW_USERLIST_ID,						AT_INT);
		MAP_ATTR( AW_SOUND_NAME,						AT_STRING);
		MAP_ATTR( AW_CAMERA_LOCATION_TYPE,				AT_INT);
		MAP_ATTR( AW_CAMERA_LOCATION_OBJECT,			AT_STRING);
		MAP_ATTR( AW_CAMERA_LOCATION_SESSION,			AT_INT);
		MAP_ATTR( AW_CAMERA_TARGET_TYPE,				AT_INT);
		MAP_ATTR( AW_CAMERA_TARGET_OBJECT,				AT_INT);
		MAP_ATTR( AW_CAMERA_TARGET_SESSION,				AT_INT);
		MAP_ATTR( AW_PLUGIN_STRING,						AT_STRING);
		MAP_ATTR( AW_BOTMENU_TO_SESSION,				AT_INT);
		MAP_ATTR( AW_BOTMENU_FROM_NAME,					AT_STRING);
		MAP_ATTR( AW_BOTMENU_FROM_SESSION,				AT_INT);
		MAP_ATTR( AW_BOTMENU_QUESTION,					AT_STRING);
		MAP_ATTR( AW_BOTMENU_ANSWER,					AT_STRING);

		MAP_ATTR( AW_CONTACT_NUMBER,					AT_INT);
		MAP_ATTR( AW_CONTACT_STATUS,					AT_INT);
		MAP_ATTR( AW_CONTACT_NAME,						AT_STRING);
		MAP_ATTR( AW_CONTACT_WORLD,						AT_STRING);
		MAP_ATTR( AW_CONTACT_MORE,						AT_BOOL);
		MAP_ATTR( AW_CONTACT_OPTIONS,					AT_INT);
		MAP_ATTR( AW_TELEGRAM_TO,						AT_STRING);
		MAP_ATTR( AW_TELEGRAM_FROM,						AT_STRING);
		MAP_ATTR( AW_TELEGRAM_TEXT,						AT_STRING);
		MAP_ATTR( AW_TELEGRAM_SENT,						AT_STRING);
		MAP_ATTR( AW_TELEGRAM_MORE,						AT_BOOL);
		MAP_ATTR( AW_JOIN_NAME,							AT_STRING);
		MAP_ATTR( AW_JOIN_CITIZEN,						AT_INT);
		MAP_ATTR( AW_JOIN_WORLD,						AT_STRING);
		MAP_ATTR( AW_JOIN_X,							AT_INT);
		MAP_ATTR( AW_JOIN_Y,							AT_INT);
		MAP_ATTR( AW_JOIN_Z,							AT_INT);
		MAP_ATTR( AW_JOIN_Y,							AT_INT);
		MAP_ATTR( AW_REGISTER_CC_NAME,					AT_STRING);
		MAP_ATTR( AW_REGISTER_CC_NUMBER,				AT_INT);
		MAP_ATTR( AW_REGISTER_CC_MONTH,					AT_INT);
		MAP_ATTR( AW_REGISTER_CC_YEAR,					AT_INT);
		MAP_ATTR( AW_REGISTER_ADDRESS,					AT_STRING);	
		MAP_ATTR( AW_REGISTER_CITY,						AT_STRING);
		MAP_ATTR( AW_REGISTER_STATE,					AT_STRING);
		MAP_ATTR( AW_REGISTER_ZIP,						AT_INT);
		MAP_ATTR( AW_REGISTER_PHONE_NUMBER,				AT_STRING);
		MAP_ATTR( AW_REGISTER_BUSINESS_NAME,			AT_STRING);
		MAP_ATTR( AW_REGISTER_VENDOR,					AT_STRING);
		MAP_ATTR( AW_REGISTER_RESULT,					AT_INT);
		MAP_ATTR( AW_REGISTER_METHOD,					AT_INT);
		MAP_ATTR( AW_VOIP_DATA,							AT_INT);

		MAP_ATTR( AW_UNIVERSE_CAV_PATH,					AT_STRING);
		MAP_ATTR( AW_ENTITY_TYPE,						AT_INT);
		MAP_ATTR( AW_ENTITY_ID,							AT_INT);
		MAP_ATTR( AW_ENTITY_STATE,						AT_INT);
		MAP_ATTR( AW_ENTITY_FLAGS,						AT_INT);
		MAP_ATTR( AW_ENTITY_X,							AT_INT);
		MAP_ATTR( AW_ENTITY_Y,							AT_INT);
		MAP_ATTR( AW_ENTITY_Z,							AT_INT);
		MAP_ATTR( AW_ENTITY_Y,							AT_INT);
		MAP_ATTR( AW_ENTITY_PITCH,						AT_INT);
		MAP_ATTR( AW_ENTITY_ROLL,						AT_INT);
		MAP_ATTR( AW_ENTITY_OWNER_SESSION,				AT_INT);
		MAP_ATTR( AW_ENTITY_OWNER_CITIZEN,				AT_INT);
		MAP_ATTR( AW_AVATAR_DISTANCE,					AT_INT);
		MAP_ATTR( AW_AVATAR_ANGLE,						AT_INT);
		MAP_ATTR( AW_AVATAR_PITCH_DELTA,				AT_INT);
		MAP_ATTR( AW_AVATAR_WORLD_INSTANCE,				AT_INT);
		MAP_ATTR( AW_ATTRIB_SENDER_SESSION,				AT_INT);
		MAP_ATTR( AW_ENTITY_MODEL_NUM,					AT_INT);	
		MAP_ATTR( AW_WORLD_V4_OBJECTS_RIGHT,			AT_STRING);
		MAP_ATTR( AW_CITIZEN_LAST_ADDRESS,				AT_IP);
		MAP_ATTR( AW_HUD_ELEMENT_TYPE,					AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_ID,					AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_SESSION,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_ORIGIN,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_X,						AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_Y,						AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_Z,						AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_FLAGS,					AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_TEXT,					AT_STRING);
		MAP_ATTR( AW_HUD_ELEMENT_COLOR,					AT_RGB);
		MAP_ATTR( AW_HUD_ELEMENT_OPACITY,				AT_FLOAT);
		MAP_ATTR( AW_HUD_ELEMENT_SIZE_X,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_SIZE_Y,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_SIZE_Z,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_CLICK_X,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_CLICK_Y,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_CLICK_Z,				AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_TEXTURE_OFFSET_X,		AT_INT);
		MAP_ATTR( AW_HUD_ELEMENT_TEXTURE_OFFSET_Y,		AT_INT);

		MAP_ATTR( AW_CITIZEN_PRIVACY,					AT_INT);
	}

#define MAP_EVENT(attr)								\
	m_items[attr].event_id		= attr;				\
	m_items[attr].name			= #attr;

	EventToStringMap::EventToStringMap()
	{
		MAP_EVENT( AW_EVENT_AVATAR_ADD );
		MAP_EVENT( AW_EVENT_AVATAR_CHANGE );
		MAP_EVENT( AW_EVENT_AVATAR_DELETE );
		MAP_EVENT( AW_EVENT_CELL_BEGIN );
		MAP_EVENT( AW_EVENT_CELL_OBJECT );
		MAP_EVENT( AW_EVENT_CELL_END );
		MAP_EVENT( AW_EVENT_CHAT );
		MAP_EVENT( AW_EVENT_OBJECT_ADD );
		MAP_EVENT( AW_EVENT_OBJECT_DELETE );
		MAP_EVENT( AW_EVENT_UNIVERSE_ATTRIBUTES );
		MAP_EVENT( AW_EVENT_UNIVERSE_DISCONNECT );
		MAP_EVENT( AW_EVENT_WORLD_ATTRIBUTES );
		MAP_EVENT( AW_EVENT_WORLD_INFO );
		MAP_EVENT( AW_EVENT_WORLD_DISCONNECT );
		MAP_EVENT( AW_EVENT_SEND_FILE );
		MAP_EVENT( AW_EVENT_CONTACT_STATE );
		MAP_EVENT( AW_EVENT_TELEGRAM );
		MAP_EVENT( AW_EVENT_JOIN );
		MAP_EVENT( AW_EVENT_OBJECT_CLICK );
		MAP_EVENT( AW_EVENT_OBJECT_SELECT );
		MAP_EVENT( AW_EVENT_AVATAR_CLICK );
		MAP_EVENT( AW_EVENT_URL );
		MAP_EVENT( AW_EVENT_URL_CLICK );
		MAP_EVENT( AW_EVENT_TELEPORT );
		MAP_EVENT( AW_EVENT_ADMIN_WORLD_INFO );
		MAP_EVENT( AW_EVENT_ADMIN_WORLD_DELETE );
		MAP_EVENT( AW_EVENT_TERRAIN_BEGIN );
		MAP_EVENT( AW_EVENT_TERRAIN_DATA );
		MAP_EVENT( AW_EVENT_TERRAIN_END );
		MAP_EVENT( AW_EVENT_CONSOLE_MESSAGE );
		MAP_EVENT( AW_EVENT_TERRAIN_CHANGED );
		MAP_EVENT( AW_EVENT_BOTGRAM );
		MAP_EVENT( AW_EVENT_TOOLBAR_CLICK );
		MAP_EVENT( AW_EVENT_USER_INFO );
		MAP_EVENT( AW_EVENT_VOIP_DATA );
		MAP_EVENT( AW_EVENT_NOISE );
		MAP_EVENT( AW_EVENT_CAMERA );
		MAP_EVENT( AW_EVENT_BOTMENU );
		MAP_EVENT( AW_EVENT_OBJECT_BUMP );
		MAP_EVENT( AW_EVENT_ENTITY_ADD );
		MAP_EVENT( AW_EVENT_ENTITY_CHANGE );
		MAP_EVENT( AW_EVENT_ENTITY_DELETE );
		MAP_EVENT( AW_EVENT_ENTITY_RIDER_ADD );
		MAP_EVENT( AW_EVENT_ENTITY_RIDER_DELETE );
		MAP_EVENT( AW_EVENT_ENTITY_RIDER_CHANGE );
		MAP_EVENT( AW_EVENT_AVATAR_RELOAD );
		MAP_EVENT( AW_EVENT_ENTITY_LINKS );
		MAP_EVENT( AW_EVENT_HUD_CLICK );
		MAP_EVENT( AW_EVENT_HUD_CREATE );
		MAP_EVENT( AW_EVENT_HUD_DESTROY );
		MAP_EVENT( AW_EVENT_HUD_CLEAR );
	}
}