// EclipseEvolutionDialog.cpp : implementation file
//

#include "stdafx.h"
#include "EclipseEvolutionDialog.h"

BEGIN_MESSAGE_MAP(EclipseEvolutionDialog, CDialog)
	ON_WM_PAINT()
	ON_WM_QUERYDRAGICON()
	//}}AFX_MSG_MAP
	ON_COMMAND(ID_BOT_PROFILES, &EclipseEvolutionDialog::OnBot_Profiles)
	ON_COMMAND(ID_BOT_LOGIN, &EclipseEvolutionDialog::OnBotLogin)
	ON_COMMAND(ID_BOT_DISCONNECT, &EclipseEvolutionDialog::OnBot_Disconnect)
	ON_COMMAND(ID_BOT_EXIT_WORLD, &EclipseEvolutionDialog::OnBot_ExitWorld)
	ON_COMMAND(ID_BOT_TELEPORT, &EclipseEvolutionDialog::OnBot_Teleport)
	ON_COMMAND(ID_MOVE_TO_HOME, &EclipseEvolutionDialog::OnMoveToHome)
	ON_COMMAND(ID_MOVE_TO_SAFETY_LOCATION, &EclipseEvolutionDialog::OnBot_MoveToSafetyLocation)
	ON_COMMAND(ID_MOVETO_GROUND_ZERO, &EclipseEvolutionDialog::OnBot_MoveToGroundZero)
	ON_COMMAND(ID_VIEW_OPTIONS, &EclipseEvolutionDialog::OnView_Options)
	ON_COMMAND(ID_UNIVERSE_OPTIONS, &EclipseEvolutionDialog::OnUniverse_Options)
	ON_COMMAND(ID_UNIVERSE_CHANGE_WELCOME_MESSAGE, &EclipseEvolutionDialog::OnUniverse_ChangeWelcomeMessage)
	ON_COMMAND(ID_UNIVERSE_EJECTIONS, &EclipseEvolutionDialog::OnUniverse_Ejections)
	ON_COMMAND(ID_UNIVERSE_CITIZEN_OPTIONS, &EclipseEvolutionDialog::OnUniverse_CitizenOptions)
	ON_COMMAND(ID_UNIVERSE_LOOKUP_CITIZEN_BY_NAME, &EclipseEvolutionDialog::OnUniverse_LookupCitizenByName)
	ON_COMMAND(ID_UNIVERSE_LOOKUP_CITIZEN_BY_NUMBER, &EclipseEvolutionDialog::OnUniverse_LookupCitizenByNumber)
	ON_COMMAND(ID_UNIVERSE_WORLD_OPTIONS, &EclipseEvolutionDialog::OnUniverse_WorldOptions)
	ON_COMMAND(ID_UNIVERSE_LOOKUP_WORLD_BY_NAME, &EclipseEvolutionDialog::OnUniverse_LookupWorldByName)
	ON_COMMAND(ID_WORLD_OPTIONS, &EclipseEvolutionDialog::OnWorld_Options)
	ON_COMMAND(ID_WORLD_CHANGE_WELCOME_MESSAGE, &EclipseEvolutionDialog::OnWorld_ChangeWelcomeMessage)
	ON_COMMAND(ID_WORLD_EJECTIONS, &EclipseEvolutionDialog::OnWorld_Ejections)
	ON_COMMAND(ID_COMMS_CONSOLE_MESSAGE, &EclipseEvolutionDialog::OnComms_ConsoleMessage)
	ON_COMMAND(ID_COMMS_CONSOLE_BROADCAST, &EclipseEvolutionDialog::OnComms_ConsoleBroadcast)
	ON_COMMAND(ID_HERMES_COMMANDS_BEGIN, &EclipseEvolutionDialog::OnComms_Hermes_CommandsBegin)
	ON_COMMAND(ID_HERMES_COMMANDS_PASSIVE_ON, &EclipseEvolutionDialog::OnComms_Hermes_PassiveOn)
	ON_COMMAND(ID_HERMES_COMMANDS_PASSIVE_OFF, &EclipseEvolutionDialog::OnComms_Hermes_PassiveOff)
	ON_COMMAND(ID_HERMES_COMMANDS_END, &EclipseEvolutionDialog::OnComms_Hermes_End)
	ON_COMMAND(ID_EVOLUTIONGCS_COMMANDS_RATIOS, &EclipseEvolutionDialog::OnComms_Eclipse_Ratios)
	ON_COMMAND(ID_EVOLUTIONGCS_COMMANDS_PRESENT, &EclipseEvolutionDialog::OnComms_Eclipse_Present)
	ON_COMMAND(ID_EVOLUTIONGCS_COMMANDS_WORLD_LIGHTING, &EclipseEvolutionDialog::OnComms_Eclipse_WorldLighting)
	ON_COMMAND(ID_EVOLUTIONGCS_COMMANDS_VERSION, &EclipseEvolutionDialog::OnComms_Eclipse_Version)
	ON_COMMAND(ID_EVOLUTIONGCS_COMMANDS_WORLD_INFO, &EclipseEvolutionDialog::OnComms_Eclipse_WorldInfo)
	ON_COMMAND(ID_XELAGOT_COMMANDS_REPORT, &EclipseEvolutionDialog::OnComms_Xelagot_Report)
	ON_COMMAND(ID_XELAGOT_COMMANDS_STUPID_BOT, &EclipseEvolutionDialog::OnComms_Xelagot_StupidBot)
	ON_COMMAND(ID_SUPPORT_URL_MESSAGE, &EclipseEvolutionDialog::OnSupport_UrlMessage)
	ON_COMMAND(ID_SUPPORT_URL_BROADCAST, &EclipseEvolutionDialog::OnSupport_UrlBroadcast)
	ON_COMMAND(ID_REPORTS_AVATAR, &EclipseEvolutionDialog::OnReports_Avatar)
	ON_COMMAND(ID_HELP_ABOUT, &EclipseEvolutionDialog::OnHelp_About)
	ON_COMMAND(ID_HELP_CHECK_FOR_UPGRADES, &EclipseEvolutionDialog::OnHelp_CheckForUpgrades)
	ON_COMMAND(ID_HELP_VISITTHEWEBSITE, &EclipseEvolutionDialog::OnHelp_VisitTheWebsite)
	ON_WM_SIZE()
	ON_WM_TIMER()
	ON_COMMAND(ID_WORLD_IMPORT_SETTINGS, &EclipseEvolutionDialog::OnWorld_Importsettings)
	ON_COMMAND(ID_WORLD_EXPORT_SETTINGS, &EclipseEvolutionDialog::OnWorld_Exportsettings)
	ON_COMMAND(ID_SECUITY_RIGHTSMANAGER, &EclipseEvolutionDialog::OnSecuity_RightsManager)
	ON_COMMAND(ID_AVATAR_EJECTION_EJECT, &EclipseEvolutionDialog::OnAvatar_Eject)
	ON_COMMAND(ID_AVATAR_EJECTION_TELEPORT, &EclipseEvolutionDialog::OnAvatar_Teleport)
	ON_COMMAND(ID_AVATAR_CLICK_ONCE, &EclipseEvolutionDialog::OnAvatar_ClickOnce)
	ON_COMMAND(ID_AVATAR_CLICK_X10, &EclipseEvolutionDialog::OnAvatar_ClickTimes10)
	ON_COMMAND(ID_AVATAR_FOLLOW_NORMAL, &EclipseEvolutionDialog::OnAvatar_FollowNormal)
	ON_COMMAND(ID_AVATAR_FOLLOW_BEHIND, &EclipseEvolutionDialog::OnAvatar_FollowBehind)
	ON_COMMAND(ID_AVATAR_CIRCLE, &EclipseEvolutionDialog::OnAvatar_Circle)
	ON_COMMAND(ID_AVATAR_GOTO, &EclipseEvolutionDialog::OnAvatar_Goto)
	ON_COMMAND(ID_AVATAR_SHOW_REPORT, &EclipseEvolutionDialog::OnAvatar_ShowReport)
	ON_COMMAND(ID_AVATAR_SHOW_DRS_PROFILE, &EclipseEvolutionDialog::OnAvatar_ShowDrsProfile)
	ON_COMMAND(ID_SUPPORT_ZONE_CONFIG, &EclipseEvolutionDialog::OnSupport_Zones_Config)
	ON_COMMAND(ID_REPORTS_AVATAR_HISTORY, &EclipseEvolutionDialog::OnReports_AvatarHistory)
	ON_COMMAND(ID_COMMS_REPEATER_WINDOW, &EclipseEvolutionDialog::OnComms_RepeaterWindow)
	ON_COMMAND(ID_SUPPORT_AVATAR_RESTRICTIONS, &EclipseEvolutionDialog::OnSupport_AvatarRestrictions)
	ON_COMMAND(ID_SUPPORT_CONFIGURE_GCS, &EclipseEvolutionDialog::OnSupport_ConfigureGcs)
	ON_NOTIFY(NM_RCLICK, IDC_SIDE_USER_LIST, &EclipseEvolutionDialog::OnSideUsers_RightClick)
	ON_WM_CLOSE()
	ON_COMMAND(ID_UNIVERSE_CREATE_CITIZEN, &EclipseEvolutionDialog::OnUniverse_CreateCitizen)
	ON_WM_SYSCOMMAND()
	ON_COMMAND(ID_AVATAR_SEND_NOISE, &EclipseEvolutionDialog::OnAvatar_SendNoise)
	ON_COMMAND(ID_VIEW_MAP, &EclipseEvolutionDialog::OnView_Map)
	ON_COMMAND(ID_COMMS_MUTELIST, &EclipseEvolutionDialog::OnComms_MuteList)
	ON_COMMAND(ID_COMMS_CONSOLEMUTELIST, &EclipseEvolutionDialog::OnComms_ConsoleMuteList)
	ON_COMMAND(ID_AVATAR_CHANGE_DISPLAY_COLOUR, &EclipseEvolutionDialog::OnAvatar_ChangeDisplayColour)
	ON_COMMAND(ID_VIEW_CHAT_SETUP, &EclipseEvolutionDialog::OnView_ChatSetup)
	ON_NOTIFY(NM_DBLCLK, IDC_SIDE_USER_LIST, &EclipseEvolutionDialog::OnSideUsers_DoubleClick)
	ON_NOTIFY(NM_DBLCLK, IDC_WHISPER_LIST, &EclipseEvolutionDialog::WhisperTargets_OnDoubleClick)
	ON_COMMAND(ID_AVATAR_RELAY_JOIN, &EclipseEvolutionDialog::OnAvatar_RelayJoin)
	ON_COMMAND(ID_AVATAR_RELAY_KICK, &EclipseEvolutionDialog::OnAvatar_RelayKick)
	ON_COMMAND(ID_AVATAR_RELAY_BAN, &EclipseEvolutionDialog::OnAvatar_RelayBan)
	ON_COMMAND(ID_AVATAR_RELAY_PASSIVE_ON, &EclipseEvolutionDialog::OnAvatar_RelayPassiveOn)
	ON_COMMAND(ID_AVATAR_RELAY_PASSIVE_OFF, &EclipseEvolutionDialog::OnAvatar_RelayPassiveOff)
	ON_COMMAND(ID_AVATAR_RELAY_LEAVE, &EclipseEvolutionDialog::OnAvatar_RelayLeave)
	ON_COMMAND(ID_SECUITY_WORD_FILTER, &EclipseEvolutionDialog::OnSecuity_SystemWordFilter)
	ON_COMMAND(ID_SECUITY_FLOOD_PREVENTION_POLICY, &EclipseEvolutionDialog::OnSecuity_FloodPreventionPolicy)
	ON_COMMAND(ID_DATABASE_QUERY_NAME, &EclipseEvolutionDialog::OnAvatar_DatabaseQueryName)
	ON_COMMAND(ID_DATABASE_QUERY_CITIZEN, &EclipseEvolutionDialog::OnAvatar_DatabaseQueryCitizen)
	ON_COMMAND(ID_DATABASE_QUERY_PRIVILEGE, &EclipseEvolutionDialog::OnAvatar_DatabaseQueryPrivilege)
	ON_COMMAND(ID_DATABASE_QUERY_IP_ADDRESS, &EclipseEvolutionDialog::OnAvatar_DatabaseQueryIpAddress)
	ON_COMMAND(ID_DATABASE_QUERY_DNS_ADDRESS, &EclipseEvolutionDialog::OnAvatar_DatabaseQueryDnsAddress)
	ON_COMMAND(ID_WORLD_QUERY_MANAGER, &EclipseEvolutionDialog::OnWorld_QueryManager)
	ON_COMMAND(ID_SUPPORT_ZONEEDITOR, &EclipseEvolutionDialog::OnSupport_ZoneEditor)
	ON_COMMAND(ID_AVATAR_CHANGE_GLOBAL_RELAY_COLOUR, &EclipseEvolutionDialog::OnAvatar_ChangeGlobalRelayColour)
	ON_COMMAND(ID_AVATAR_CHANGE_GLOBAL_RELAY_SETTINGS, &EclipseEvolutionDialog::OnAvatar_ChangeGlobalRelaySettings)
	ON_COMMAND(ID_SUPPORT_IP, &EclipseEvolutionDialog::OnSupport_IpDnsAnnouncement)
	ON_COMMAND(ID_BOT_SAVESTATUS, &EclipseEvolutionDialog::OnBot_Savestatus)
	ON_COMMAND(ID_BOT_CRASHBOT, &EclipseEvolutionDialog::OnBot_Crashbot)
	ON_COMMAND(ID_SUPPORT_RELAYMANAGEMENT, &EclipseEvolutionDialog::OnSupport_RelayManagement)
	ON_COMMAND(ID_BOT_SHUTDOWN, &EclipseEvolutionDialog::OnBot_Shutdown)
	ON_COMMAND(ID_SUPPORT_HEADSUP, &EclipseEvolutionDialog::OnSupport_HeadsUp)
	ON_COMMAND(ID_AVATAR_ASSUME_AVATAR, &EclipseEvolutionDialog::OnAvatar_AssumeAvatar)
	ON_COMMAND(ID_UNIVERSE_LOOKUP_CITIZEN, &EclipseEvolutionDialog::OnAvatar_LookupCitizen)
	ON_COMMAND(ID_UNIVERSE_LOOKUP_PRIVILEGE, &EclipseEvolutionDialog::OnAvatar_LookupPrivilege)
	ON_COMMAND(ID_VIEW_CLEAR_MAIN_LOG, &EclipseEvolutionDialog::OnView_ClearMainLog)
	ON_COMMAND(ID_COMMS_BOTGRAM_EMAIL, &EclipseEvolutionDialog::OnComms_BotgramEmail)
	ON_COMMAND(ID_SUPPORT_SCRIPTING_EDITOR, &EclipseEvolutionDialog::OnSupport_ScriptingEditor)
	ON_COMMAND(ID_SUPPORT_MOVERCONTROL, &EclipseEvolutionDialog::OnSupport_MoverControl)
	ON_COMMAND(ID_VIEW_SELECTCHAT, &EclipseEvolutionDialog::OnView_SelectChat)
	ON_COMMAND(ID_VIEW_SELECTWHISPER, &EclipseEvolutionDialog::OnView_SelectWhisper)
	ON_COMMAND(ID_VIEW_SELECTCOMMANDS, &EclipseEvolutionDialog::OnView_SelectCommands)
	ON_COMMAND(ID_VIEW_SELECTCONSOLE, &EclipseEvolutionDialog::OnView_SelectConsole)
	ON_COMMAND(ID_VIEW_SELECTCONSOLEMODE, &EclipseEvolutionDialog::OnView_SelectConsoleMode)
	ON_COMMAND(ID_WORLD_BACKUPWORLD, &EclipseEvolutionDialog::OnWorld_BackupView)
	ON_COMMAND(ID_FEATURES_RECORDER, &EclipseEvolutionDialog::OnFeatures_Recorder)
	ON_COMMAND(ID_RELAYMANAGEMENT_CHANNELEDITOR, &EclipseEvolutionDialog::OnFeatures_RelayChannelEditor)
	ON_COMMAND(ID_COMMUNICATIONS_BOTGRAM_TO_CITIZEN, &EclipseEvolutionDialog::OnAvatar_BotgramToCitizen)
	ON_COMMAND(ID_COMMUNICATIONS_BOTGRAM_TO_PRIVILEGE, &EclipseEvolutionDialog::OnAvatar_BotgramToPrivilege)
	ON_COMMAND(ID_FEATURES_SCRIPTINGCISCOMMANDS, &EclipseEvolutionDialog::OnFeatures_ScriptingCisCommands)
	ON_COMMAND(ID_REPORTS_IPOWNERSHIPANDCOLLISIONS, &EclipseEvolutionDialog::OnReports_IpOwnershipAndColissions)
	ON_COMMAND(ID_UNIVERSE_WORLDLIST, &EclipseEvolutionDialog::OnUniverse_WorldList)
	ON_NOTIFY(HDN_ITEMCLICK, 0, &EclipseEvolutionDialog::OnWorldList_HeaderClicked)
	ON_COMMAND(ID_VIEW_LAYOUT, &EclipseEvolutionDialog::OnView_Layout)
	ON_COMMAND(ID_FEATURES_JUMPPOINTSMANAGER, &EclipseEvolutionDialog::OnFeatures_JumpPointsManager)
	ON_WM_COPYDATA()
	END_MESSAGE_MAP()
