#pragma once
#include "colourbutton.h"
#include "PropertyScriptCtrl.h"
#include "worldattributes.h"

// WorldOptionsDialog dialog

const int WAG_GENERAL          = 0;
const int WAG_RIGHT            = 1;
const int WAG_GROUND           = 2;
const int WAG_OBJECT_PATH      = 3;
const int WAG_BUILDING         = 4;
const int WAG_FOG              = 5;
const int WAG_LIGHTING         = 6;
const int WAG_MOVEMENT         = 7;
const int WAG_SKY              = 8;
const int WAG_CLOUDS_1         = 9;
const int WAG_CLOUDS_2         = 10;
const int WAG_CLOUDS_3         = 11;
const int WAG_COMMUNICATIONS   = 12;
const int WAG_AVATARS          = 13;
const int WAG_WATER            = 14;
const int WAG_SOUND            = 15;

struct WORLDOPTIONS_OBJECTS
{
		TextBox*       c_pEnterRight;
		TextBox*       c_pBuildRight;
		TextBox*       c_pVoipRight;
		TextBox*       c_pEminentDomainRight;
		TextBox*       c_pSpecialObjectsRight;
		TextBox*       c_pPublicSpeakerRight;
		TextBox*       c_pBotsRight;
		TextBox*       c_pEjectRight;
		TextBox*       c_pSpeakRight;
		TextBox*       c_pSpecialCommandsRight;
		TextBox*       c_pSpecialCommands;
		TextBox*       c_pV4ObjectsRight;
		TextBox*       c_pTerrainRight;
		TextBox*       c_pTitle;
		TextBox*       c_pHomePage;
		ComboBox*      c_pRating;
		TextBox*       c_pWelcomeMessage;
		TextBox*       c_pKeywords;
		TextBox*       c_pGround;
		CButton*       c_pRepeatingGround;
		CButton*       c_pEnableTerrain;
		TextBox*       c_pTerrainAmbient;
		TextBox*       c_pTerrainDiffuse;
		TextBox*       c_pTerrainOffset;
		TextBox*       c_pObjectPath;
		TextBox*       c_pObjectRefresh;
		TextBox*       c_pObjectPassword;
		CButton*       c_pEnableReferer;
		TextBox*       c_pCavObjectPath;
		TextBox*       c_pCavObjectPassword;
		TextBox*       c_pCavObjectRefresh;
		ComboBox*      c_pCellLimit;
		TextBox*       c_pRestrictedRadius;
		TextBox*       c_pMaxLightRadius;
		CButton*       c_pDisableCreateUrl;
		CButton*       c_pAllowObjectSelect;
		CButton*       c_pAllow3AxisRotation;
		CButton*       c_pAllowTouristBuild;
		TextBox*       c_pMoverEmptyResetTimeout;
		TextBox*       c_pMoverUsedResetTimeout;
		CButton*       c_pEnableBumpEvent;
		CButton*       c_pEnableSyncEvents;
		CButton*       c_pFogEnable;
		TextBox*       c_pFogMinimum;
		TextBox*       c_pFogMaximum;
		CButton*       c_pFogTinted;
		ColourButton*  c_pFog;
		ComboBox*      c_pMinimumVisibility;
		TextBox*       c_pLightX;
		TextBox*       c_pLightY;
		TextBox*       c_pLightZ;
		ColourButton*  c_pLight;
		ColourButton*  c_pAmbientLight;
		TextBox*       c_pLightTexture;
		TextBox*       c_pLightMask;
		TextBox*       c_pLightDrawSize;
		CButton*       c_pLightDrawFront;
		CButton*       c_pLightDrawBright;
		CButton*       c_pLightSourceUseColor;
		ColourButton*  c_pLightSourceColor;
		CButton*       c_pDisableShadows;
		TextBox*       c_pEntryPoint;
		CButton*       c_pAllowPassthru;
		CButton*       c_pAllowFlying;
		CButton*       c_pAllowTeleport;
		CButton*       c_pAllowAvatarCollision;
		TextBox*       c_pGravity;
		TextBox*       c_pFriction;
		CButton*       c_pSlopeslideEnabled;
		TextBox*       c_pSlopeslideMinAngle;
		TextBox*       c_pSlopeslideMaxAngle;
		CButton*       c_pEnableCameraCollision;
		TextBox*       c_pCameraZoom;
		TextBox*       c_pBackdrop;
		TextBox*       c_pSkybox;
		ColourButton*  c_pSkyNorth;
		ColourButton*  c_pSkySouth;
		ColourButton*  c_pSkyEast;
		ColourButton*  c_pSkyWest;
		ColourButton*  c_pSkyTop;
		ColourButton*  c_pSkyBottom;
		TextBox*       c_pCloudsLayer1Texture;
		TextBox*       c_pCloudsLayer1Mask;
		TextBox*       c_pCloudsLayer1Tile;
		TextBox*       c_pCloudsLayer1SpeedX;
		TextBox*       c_pCloudsLayer1SpeedZ;
		TextBox*       c_pCloudsLayer1Opacity;
		TextBox*       c_pCloudsLayer2Texture;
		TextBox*       c_pCloudsLayer2Mask;
		TextBox*       c_pCloudsLayer2Tile;
		TextBox*       c_pCloudsLayer2SpeedX;
		TextBox*       c_pCloudsLayer2SpeedZ;
		TextBox*       c_pCloudsLayer2Opacity;
		TextBox*       c_pCloudsLayer3Texture;
		TextBox*       c_pCloudsLayer3Mask;
		TextBox*       c_pCloudsLayer3Tile;
		TextBox*       c_pCloudsLayer3SpeedX;
		TextBox*       c_pCloudsLayer3SpeedZ;
		TextBox*       c_pCloudsLayer3Opacity;
		CButton*       c_pDisableChat;
		CButton*       c_pAllowCitizenWhisper;
		CButton*       c_pAllowTouristWhisper;
		CButton*       c_pAlwaysShowNames;
		CButton*       c_pDisableAvatarList;
		TextBox*       c_pAvatarRefreshRate;
		CStatic*       c_p26347;
		CButton*       c_pEnableCavAwEnableCavCitizen;
		CButton*       c_pEnableCavAwEnableCavBot;
		CButton*       c_pEnableCavAwEnableCavTourist;
		CButton*       c_pEnableCavAwEnableCavWorldCitizen;
		CButton*       c_pEnableCavAwEnableCavWorldBot;
		CButton*       c_pEnableCavAwEnableCavWorldTourist;
		CButton*       c_pEnablePav;
		CButton*       c_pChatDisableUrlClicks;
		CButton*       c_pDisableMultipleMedia;
		TextBox*       c_pBotmenuUrl;
		CButton*       c_pVoipConferenceGlobal;
		CButton*       c_pVoipModerateGlobal;
		CButton*       c_pWaterEnabled;
		TextBox*       c_pWaterTexture;
		TextBox*       c_pWaterMask;
		TextBox*       c_pWaterBottomTexture;
		TextBox*       c_pWaterBottomMask;
		TextBox*       c_pWaterOpacity;
		TextBox*       c_pWaterVisibility;
		ColourButton*  c_pWater;
		TextBox*       c_pWaterLevel;
		TextBox*       c_pWaterSurfaceMove;
		TextBox*       c_pWaterWaveMove;
		TextBox*       c_pWaterSpeed;
		TextBox*       c_pBuoyancy;
		TextBox*       c_pWaterFriction;
		CButton*       c_pWaterUnderTerrain;
		TextBox*       c_pSoundFootstep;
		TextBox*       c_pSoundWaterEnter;
		TextBox*       c_pSoundWaterExit;
		TextBox*       c_pSoundAmbient;

};